// P-1 Build 4 — Demo seed: one demo org, 5 experts across all 3 personas,
// 2-3 frameworks each, captured via the REAL methodology-router pipeline.
//
// "Real pipeline, not raw SQL inserts" means: every framework artifact in
// this seed is generated by an actual call to claude-sonnet-5 using the
// SAME frame-pattern.md prompt template /api/codify/answer uses in
// production (verbatim-copied helpers below, same pattern scripts/
// codify-smoke.mjs already established for the P-0 acceptance harness).
// What's scripted rather than live is the Q&A ladder itself — these 14
// records' fields are pre-written (a real interactive 5-13 question session
// per record would mean ~100+ sequential model calls just to seed a demo),
// but every framework you see in the library was actually rendered by the
// model from those fields, not fabricated JSON. Documented as a deliberate
// scope call in DECISION-LOG (P-1 close-out) — flag it if you want full
// interactive-session seeding instead.
//
// Idempotent: re-running finds the existing demo org / users and skips
// re-inserting records if the org already has the expected count. Pass
// --force to wipe and reseed (deletes this demo org's pattern_records only,
// via the demo org's id — never touches Brian's real/grandfathered org).
//
// Usage: node scripts/seed-p1-demo.mjs [--force]
import Anthropic from "@anthropic-ai/sdk";
import { createClient } from "@supabase/supabase-js";
import { readFile } from "node:fs/promises";
import path from "node:path";

// ─── env (same .env.local loader as scripts/codify-smoke.mjs) ───
const envRaw = await readFile(path.join(process.cwd(), ".env.local"), "utf-8");
for (const line of envRaw.split(/\r?\n/)) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].trim();
}

const FORCE = process.argv.includes("--force");

const anthropic = new Anthropic();
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const DEMO_ORG_NAME = "Meridian Precision Manufacturing (DEMO)";
const DEMO_PASSWORD = "Demo-Meridian-2026!"; // same for all 5 — this is a demo, not a real account

// ─── verbatim from src/lib/claude.ts / src/lib/elicitation.ts ───
// (same copy-don't-import approach as scripts/codify-smoke.mjs — this is a
// plain Node script, not bundled through Next, so TS libs aren't importable
// directly.)
function firstText(content) {
  const block = content.find((b) => b.type === "text");
  return block?.text ?? "";
}
function parseJson(text) {
  try {
    return JSON.parse(text.replace(/^```json?\n?|```$/g, "").trim());
  } catch {
    return null;
  }
}
function parseJsonLoose(text) {
  const direct = parseJson(text);
  if (direct !== null) return direct;
  const stripped = text.replace(/^```json?\n?|```$/g, "").trim();
  const start = stripped.search(/[{[]/);
  if (start === -1) return null;
  const open = stripped[start];
  const close = open === "{" ? "}" : "]";
  let depth = 0, inStr = false, esc = false;
  for (let i = start; i < stripped.length; i++) {
    const ch = stripped[i];
    if (inStr) {
      if (esc) esc = false;
      else if (ch === "\\") esc = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') { inStr = true; continue; }
    if (ch === open) depth++;
    else if (ch === close) {
      depth--;
      if (depth === 0) {
        try { return JSON.parse(stripped.slice(start, i + 1)); }
        catch { return null; }
      }
    }
  }
  return null;
}
function isFrameworkArtifact(v) {
  if (!v || typeof v !== "object") return false;
  const f = v;
  const isStrArr = (x) => Array.isArray(x) && x.length > 0 && x.every((s) => typeof s === "string");
  return (
    typeof f.name === "string" &&
    typeof f.tagline === "string" &&
    isStrArr(f.when_to_apply) &&
    isStrArr(f.signals) &&
    typeof f.the_play === "string" &&
    typeof f.why_it_works === "string" &&
    isStrArr(f.boundaries)
  );
}
function formatRecordState(fields) {
  return JSON.stringify(fields, null, 2);
}
const frameTemplate = await readFile(path.join(process.cwd(), "prompts", "frame-pattern.md"), "utf-8");
async function framePattern(fields) {
  const prompt = frameTemplate.replaceAll("{{record}}", formatRecordState(fields));
  for (let attempt = 0; attempt < 3; attempt++) {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-5",
      max_tokens: 3072,
      messages: [{ role: "user", content: prompt }],
    });
    const text = firstText(msg.content);
    const parsed = text ? parseJsonLoose(text) : null;
    if (isFrameworkArtifact(parsed)) return parsed;
  }
  return null;
}

// ─── method fallback questions, verbatim subset from src/lib/elicitation.ts ───
// Used only to build a realistic qa_pairs transcript for each seeded record —
// the SAME wording the live ladder would fall back to for this method.
const METHOD_Q = {
  "5whys_fishbone": {
    signal: "What broke, specifically — what did you see, hear, or measure that told you something had failed?",
    reasoning: "Why did that actually cause the failure — walk the chain of causes, not just the first domino.",
    entity: "Which machine or equipment, which process step, and what error type was this? Name the specific asset if there is one.",
    boundaries: "Where would this same fix NOT hold — a different machine, a different failure mode, a different scale?",
  },
  aar_success_case: {
    signal: "What specifically happened that made this a win — the concrete moment or decision, not just the outcome?",
    reasoning: "Why did that approach work — what made it the right move rather than the default one?",
    entity: "Who was involved in making this work, and who else benefits downstream? Names are fine — they stay internal to your org.",
    boundaries: "Under what conditions would this NOT work as well — a different team, a different starting point, a different scale?",
  },
  premortem: {
    signal: "What specifically are you worried could go wrong — the concrete failure mode, not just a general worry?",
    reasoning: "Why is that risk real — what would have to be true for it to actually happen?",
    entity: "What equipment, process, team, or department would bear this risk if it played out?",
    boundaries: "Under what conditions would this risk NOT apply, or your mitigation fail?",
  },
  a3: {
    signal: "What specifically keeps recurring — the concrete gap between what should happen and what actually does?",
    reasoning: "Why does that gap keep recurring instead of getting fixed for good?",
    entity: "Which process, department, or role does this friction keep showing up in?",
    boundaries: "Where does this correction NOT apply — a different process, or a different root cause?",
  },
  cdm: {
    signal: "What specifically did you notice that told you this was a critical moment — the cue someone else might have missed?",
    reasoning: "Why was that the right call rather than the obvious alternative?",
    entity: "Who made this call, who else was involved, and who's affected by it? Names are fine — they stay internal to your org.",
    boundaries: "Where would this same call have been the WRONG one?",
  },
};
const OPENING_QUESTION =
  "Think of a recent situation you'd want captured — the one you just flagged. " +
  "To start: roughly how big is the org, what part of the business, and what was going on?";
const GENERIC_CLASSIFY = "What did you observe that told you something needed to change — what prompted your involvement?";
const GENERIC_CALL = "What did you recommend, or what call did you make?";

function buildQaPairs(fields, method) {
  const m = METHOD_Q[method];
  const entityNames = fields.entity_map.map((e) => e.name).join(", ");
  return [
    { rung: 1, question: OPENING_QUESTION, answer: fields.context_summary },
    { rung: 2, question: GENERIC_CLASSIFY, answer: fields.trigger_signal },
    { rung: 3, question: GENERIC_CALL, answer: fields.judgment },
    { rung: 4, question: m.signal, answer: fields.signal_detail },
    { rung: 5, question: m.reasoning, answer: fields.rationale },
    { rung: 6, question: m.entity, answer: entityNames },
    { rung: 7, question: m.boundaries, answer: fields.boundaries },
  ];
}

// ─── 5 demo experts, all 3 personas represented ───
const EXPERTS = [
  { key: "elena", email: "elena.ruiz@meridian-demo.example", display_name: "Elena Ruiz", persona: "exec", title: "VP Operations" },
  { key: "david", email: "david.chen@meridian-demo.example", display_name: "David Chen", persona: "technical_director", title: "Technical Director, Manufacturing Engineering" },
  { key: "priya", email: "priya.nair@meridian-demo.example", display_name: "Priya Nair", persona: "technical_director", title: "Technical Director, Quality Systems" },
  { key: "tom", email: "tom.whitfield@meridian-demo.example", display_name: "Tom Whitfield", persona: "sr_manager", title: "Sr. Manager, Maintenance" },
  { key: "angela", email: "angela.brooks@meridian-demo.example", display_name: "Angela Brooks", persona: "sr_manager", title: "Sr. Manager, 2nd Shift Production" },
];

// ─── 14 pattern records, mid-market manufacturing domain (presses, CNC,
// changeover, QC gates, maintenance). "Marcus Webb" (2nd-shift press lead)
// is named in 3 different experts' WIN records — a corroboration cluster for
// P-4.5. "Denise Ortiz" (tooling/changeover specialist) is named in 2
// different experts' WIN records — a second, smaller cluster. Both are
// role_person entities, never one of the 5 seeded authors themselves —
// they're the subjects being recognized, not the ones capturing the record.
// daysAgo spacing: Marcus mentions land at 47/19/6 days ago (accelerating —
// a rising signal). Denise's land at 60/12 (a slower second cluster).
const RECORDS = [
  // ─── Elena Ruiz (exec) ───
  {
    expert: "elena", daysAgo: 47, trigger_type: "win", method: "aar_success_case",
    context_summary: "VP Operations at a ~350-person precision manufacturer (stamping presses + CNC machining) backed an operator-driven change to press changeover staging on Line 3.",
    context_org_size: "200-1000", context_function: "Leadership", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "Line 3's changeover between die runs was eating 90+ minutes of downtime per swap, well above the plant's other press lines.",
    signal_detail: "Marcus Webb, the 2nd-shift press lead, had quietly started pre-staging the next die and its shims during the CURRENT run instead of after it stopped — something the standard work sheet didn't call for. I noticed his shift's changeovers were finishing 30+ minutes faster and asked him to walk me through it on the floor instead of just reading his numbers on a report.",
    judgment: "Formalize Marcus's staging method as the new standard work for all three shifts, with him training the other leads directly rather than routing it through an engineering rewrite first.",
    rationale: "The fix already existed and was already proven on his shift — the fastest path to value was copying a working practice, not commissioning a redesign. Having him train peer-to-peer also carried more credibility on the floor than a memo from engineering would have.",
    boundaries: "This doesn't work if the 'better' method only works because of one person's tribal knowledge that can't be taught — here it transferred cleanly because it was a sequencing change, not a skill dependent on Marcus specifically. Where the win really is irreplaceable individual skill, you need to capture and codify it before promoting it, not just copy the behavior.",
    entity_map: [
      { type: "role_person", name: "Marcus Webb", detail: "2nd-shift press lead, Line 3" },
      { type: "equipment_asset", name: "Line 3 stamping press", detail: null },
      { type: "process", name: "Die changeover staging", detail: null },
    ],
  },
  {
    expert: "elena", daysAgo: 81, trigger_type: "concern", method: "premortem",
    context_summary: "VP Operations flagged a single-source risk on the hydraulic seal kits used across the plant's 400-ton presses before signing a renewed annual supply contract.",
    context_org_size: "200-1000", context_function: "Leadership", situation_type: "Systems", intervention_type: "Add",
    trigger_signal: "Procurement proposed renewing an exclusive annual contract with the current hydraulic seal supplier at a better unit price, since the relationship had been trouble-free for two years.",
    signal_detail: "The trouble-free record was exactly what worried me — two years without a hiccup meant we'd never actually tested what happens if their one plant has a fire, a strike, or a quality escape. A 400-ton press down for a seal kit is a full line stopped, not a minor delay, and we had zero qualified backup source identified anywhere in the file.",
    judgment: "Keep the primary supplier but require procurement to qualify a second seal-kit source before signing, even if the second source costs more per unit.",
    rationale: "The savings from single-sourcing are real but bounded; the downside of a press line down with no qualified alternate is unbounded relative to the savings. Paying a premium to keep a qualified backup live is cheap insurance against a scenario procurement's cost analysis didn't model at all.",
    boundaries: "This caution doesn't apply to low-criticality consumables where a stockout just means a short delay, not a stopped line — dual-sourcing everything would just add cost and vendor-management overhead with no matching risk to justify it.",
    entity_map: [
      { type: "department", name: "Procurement", detail: null },
      { type: "equipment_asset", name: "400-ton presses", detail: null },
      { type: "process", name: "Hydraulic seal kit sourcing", detail: null },
    ],
  },
  {
    expert: "elena", daysAgo: 68, trigger_type: "judgment", method: "cdm",
    context_summary: "VP Operations overruled the plant controller's recommendation to idle an underused CNC cell rather than keep it staffed for a small, irregular batch job.",
    context_org_size: "200-1000", context_function: "Leadership", situation_type: "Cost", intervention_type: "Restructure",
    trigger_signal: "The controller's utilization report flagged one CNC cell running at 35% capacity, mostly on a low-volume specialty part, and recommended idling it and outsourcing that part.",
    signal_detail: "The utilization number was real but it missed that this cell was the plant's only qualified fallback for three OTHER lines' overflow and rework — its 'idle' time was actually held capacity, visible on the floor as the one cell operators got sent to when something upstream broke, not visible anywhere in the controller's utilization math.",
    judgment: "Keep the cell staffed and reclassify its purpose officially as flex/overflow capacity rather than a dedicated line, instead of idling or outsourcing it.",
    rationale: "A utilization metric that only looks at a cell's own scheduled output will always recommend cutting shared slack capacity, because the value of that slack shows up on everyone else's line, not its own. Reclassifying it made the hidden function visible instead of accidentally cutting it.",
    boundaries: "If the cell genuinely had no cross-line fallback role — a true standalone underused asset — the controller's call would be right, and protecting it would just be defending a sunk cost. This only holds when the hidden shared-capacity function is real and demonstrable, not assumed.",
    entity_map: [
      { type: "equipment_asset", name: "CNC overflow cell", detail: null },
      { type: "department", name: "Finance / Controller", detail: null },
    ],
  },

  // ─── David Chen (technical_director) ───
  {
    expert: "david", daysAgo: 88, trigger_type: "broke", method: "5whys_fishbone",
    context_summary: "Technical Director of Manufacturing Engineering investigated repeated tolerance failures on CNC Line 2 after a new fixture was installed for a redesigned bracket.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "CNC Line 2 started failing final tolerance checks on roughly 1 in 8 parts within two weeks of a new fixture going into service, and the floor's first read was operator error on the new setup.",
    signal_detail: "The scrap parts weren't randomly distributed through the shift — they clustered in the first 20 minutes after any machine restart, which pointed away from operator technique and toward something physical warming up. Checking the fixture with a thermal camera showed it hadn't reached stable temperature until about 25 minutes into a run, and it was clamping half a thousandth looser cold than warm.",
    judgment: "Add a mandatory 25-minute warm-up cycle with a dummy part before production runs on that fixture, and add a physical temperature checkpoint to the fixture's own maintenance spec.",
    rationale: "The failure was a thermal-drift problem in the tooling, not a training problem in the operators — retraining people to compensate for a fixture defect would have treated the symptom and left the scrap rate exactly where it was on every future restart.",
    boundaries: "This fix doesn't apply to fixtures without meaningful thermal mass or drift — forcing a warm-up cycle onto every fixture regardless of its actual thermal behavior just burns capacity for no reason. Verify the drift exists before mandating the warm-up.",
    entity_map: [
      { type: "equipment_asset", name: "CNC Line 2 fixture", detail: "new bracket fixture" },
      { type: "error_class", name: "Tolerance failure — post-restart clamping drift", detail: null },
    ],
  },
  {
    expert: "david", daysAgo: 60, trigger_type: "win", method: "aar_success_case",
    context_summary: "Technical Director adopted a tooling specialist's fixture-indexing jig to cut changeover time on a CNC cell running frequent small-batch SKU switches.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "A CNC cell running high SKU-mix small batches was losing nearly an hour per changeover to manual fixture alignment, well above what the batch sizes could economically absorb.",
    signal_detail: "Denise Ortiz, one of our tooling specialists, had built a simple locating-pin jig off the clock to speed up her own alignment checks, and I noticed her changeovers finishing in under 20 minutes without anyone flagging it as a project. The tell was that she wasn't using the torque wrench sequence in the standard work at all — she'd replaced three alignment steps with one drop-in check.",
    judgment: "Fund a proper machined version of Denise's jig for every fixture on that cell and fold the new sequence into standard work instead of leaving it as one person's workaround.",
    rationale: "An unofficial fix that only exists because one specialist built it herself is a single point of failure — if she's out sick or leaves, the plant loses the time savings. Formalizing it protects the gain and lets every operator on the cell get it, not just her shift.",
    boundaries: "This doesn't transfer to fixtures where alignment tolerance is tight enough that a simplified locating jig would actually introduce error — Denise's fixtures had margin to spare; not every changeover step is safe to compress the same way.",
    entity_map: [
      { type: "role_person", name: "Denise Ortiz", detail: "tooling specialist" },
      { type: "process", name: "Fixture changeover alignment", detail: null },
      { type: "equipment_asset", name: "CNC small-batch cell", detail: null },
    ],
  },
  {
    expert: "david", daysAgo: 33, trigger_type: "friction", method: "a3",
    context_summary: "Technical Director addressed a chronic pattern of elevated first-part scrap specifically on Monday morning startups across three separate lines.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Measure",
    trigger_signal: "Scrap rate on the first part of the day was consistently 3-4x the intra-shift average every Monday, across lines that had nothing in common mechanically, which ruled out a single-machine cause.",
    signal_detail: "What the three lines DID have in common was that the weekend shutdown let coolant settle and machines cool fully, unlike the shorter overnight gaps other weekdays had — Monday's first part was effectively every machine's own 'cold start' problem at once, just showing up as three unrelated-looking scrap spikes instead of one obvious pattern.",
    judgment: "Add a standardized first-part-of-week verification step (dry run + measurement before releasing to production) specifically after weekend shutdowns, rather than treating each line's Monday scrap as a separate local issue.",
    rationale: "Chasing this line by line as three unrelated problems would have meant three separate root-cause efforts for what is structurally one shared-cause problem — recognizing the common weekend-cooldown driver let one correction fix all three at once.",
    boundaries: "This doesn't apply to lines that run continuously through weekends or that use materials/tooling without meaningful thermal settling — the fix targets the specific cold-start mechanism, not scrap variation generally.",
    entity_map: [
      { type: "error_class", name: "Monday first-part scrap", detail: null },
      { type: "process", name: "Weekend shutdown / restart", detail: null },
    ],
  },

  // ─── Priya Nair (technical_director) ───
  {
    expert: "priya", daysAgo: 75, trigger_type: "broke", method: "5whys_fishbone",
    context_summary: "Technical Director of Quality Systems investigated how a batch of out-of-spec mounting brackets passed the QC gate and reached final assembly.",
    context_org_size: "200-1000", context_function: "Quality", situation_type: "Process failure", intervention_type: "Remove",
    trigger_signal: "Assembly flagged brackets with an out-of-tolerance hole pattern that should have been caught at the QC gate two steps upstream, and the first assumption was an inspector skipped a step.",
    signal_detail: "The inspection log showed every step had actually been performed and signed off — the CMM probe itself had drifted out of calibration two days before its scheduled check, so the gate was measuring correctly against a reference that was quietly wrong. The tell was that ALL the flagged parts passed at nearly the same offset, which a skipped-inspection theory couldn't explain but a systematically miscalibrated tool could.",
    judgment: "Shorten the CMM probe's calibration interval and add an independent daily reference-block check rather than relying solely on the scheduled calibration window.",
    rationale: "The failure mode wasn't human — it was a tool silently drifting inside its calibration window, which no amount of retraining or discipline messaging to inspectors would have caught. Only a more frequent independent check closes that specific gap.",
    boundaries: "This wouldn't be the right fix if the actual root cause turns out to be operator skip-steps on a different gate — don't apply a calibration-frequency fix to a discipline problem; confirm which failure mode you actually have before choosing between them.",
    entity_map: [
      { type: "equipment_asset", name: "CMM probe", detail: "QC gate 2" },
      { type: "error_class", name: "Silent calibration drift", detail: null },
      { type: "department", name: "Quality", detail: null },
    ],
  },
  {
    expert: "priya", daysAgo: 12, trigger_type: "win", method: "aar_success_case",
    context_summary: "Technical Director of Quality Systems adopted a tooling specialist's changeover checklist idea to cut First Article Inspection cycle time on new SKUs.",
    context_org_size: "200-1000", context_function: "Quality", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "First Article Inspection on new SKU launches was taking most of a shift, which was pushing new-product ramp schedules out repeatedly.",
    signal_detail: "Denise Ortiz, on the engineering side, had already built a one-page pre-check sheet for her own changeovers that flagged exactly which dimensions tend to drift on a new setup — quality had never seen it because it lived on the tooling side, not the quality side. Once I saw it, most of our First Article time was actually spent re-discovering things her sheet already predicted.",
    judgment: "Adopt Denise's pre-check sheet as an input to the official First Article Inspection plan for every new SKU, instead of building FAI plans from the drawing alone each time.",
    rationale: "The tooling side already had tacit knowledge of exactly where new setups tend to drift; quality was rebuilding that knowledge from scratch on paper every launch. Connecting the two teams' information closed the gap faster than any FAI process redesign would have on its own.",
    boundaries: "This doesn't generalize to SKUs so novel that no comparable prior setup exists — Denise's sheet works because it's built on pattern recognition across similar past changeovers; a truly first-of-its-kind part still needs a full from-scratch FAI plan.",
    entity_map: [
      { type: "role_person", name: "Denise Ortiz", detail: "tooling specialist" },
      { type: "process", name: "First Article Inspection", detail: null },
      { type: "department", name: "Quality", detail: null },
    ],
  },
  {
    expert: "priya", daysAgo: 26, trigger_type: "concern", method: "premortem",
    context_summary: "Technical Director of Quality Systems raised a concern before rolling out a plan to auto-approve incoming supplier material certs above a trust score threshold.",
    context_org_size: "200-1000", context_function: "Quality", situation_type: "Systems", intervention_type: "Add",
    trigger_signal: "A proposed system upgrade would auto-approve incoming raw material certs from suppliers scoring above a trust threshold, skipping manual review to speed up receiving.",
    signal_detail: "A high trust score is built from a supplier's past performance, but past performance says nothing about whether THIS specific cert reflects a process change at their plant — the auto-approval plan had no mechanism to catch a good supplier whose process quietly changed, which is exactly the failure mode that actually causes surprise material issues.",
    judgment: "Auto-approve on trust score but require the system to flag any cert showing a different plant, batch method, or spec version than the supplier's prior certs, even from a high-trust supplier.",
    rationale: "The realistic risk isn't bad suppliers — it's good suppliers whose process shifted without anyone here noticing, and trust score alone can't detect that. Adding a change-flag check targets the actual failure mode instead of just gating on reputation.",
    boundaries: "This extra flagging is overkill for low-risk, non-critical materials where a process change wouldn't meaningfully affect the finished part — apply the stricter check to critical/regulated materials, not the whole incoming stream.",
    entity_map: [
      { type: "process", name: "Incoming material cert review", detail: null },
      { type: "department", name: "Quality", detail: null },
    ],
  },

  // ─── Tom Whitfield (sr_manager) ───
  {
    expert: "tom", daysAgo: 53, trigger_type: "friction", method: "a3",
    context_summary: "Sr. Manager of Maintenance addressed a recurring unplanned-downtime pattern on the plant's oldest stamping press, failing every few weeks from the same hydraulic valve.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Consolidate",
    trigger_signal: "Press #3 kept going down on the same hydraulic directional valve roughly every 5-6 weeks, and each time maintenance replaced the valve and moved on, treating it as a wear-and-tear part failure.",
    signal_detail: "Pulling the failure history together for the first time (instead of looking at each incident alone) showed the valve was ALWAYS failing during high-cycle runs of one specific heavy-gauge part, never during lighter jobs — it wasn't random wear, it was a duty-cycle mismatch between that valve's rating and that specific job's demand.",
    judgment: "Upgrade to a higher-duty-cycle valve rated for the heavy-gauge job specifically, rather than continuing to replace the original spec valve reactively every time it failed.",
    rationale: "Replacing the same part repeatedly without asking why it keeps failing under the SAME conditions was treating a spec mismatch as random wear — the correction had to change the part's rating, not just its age.",
    boundaries: "This doesn't apply to failures that genuinely are random or age-related across varied jobs — the fix here specifically targets a duty-cycle mismatch; don't upgrade every recurring part failure without first checking whether it clusters around one condition like this one did.",
    entity_map: [
      { type: "equipment_asset", name: "Press #3", detail: "hydraulic directional valve" },
      { type: "error_class", name: "Duty-cycle valve failure", detail: null },
    ],
  },
  {
    expert: "tom", daysAgo: 19, trigger_type: "win", method: "aar_success_case",
    context_summary: "Sr. Manager of Maintenance credited an early save on Press #3 to a 2nd-shift press lead who flagged an unusual vibration before it became a failure.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Measure",
    trigger_signal: "Press #3 ran for three full shifts with a faint vibration during its return stroke that didn't trip any alarm and wasn't part of any scheduled check.",
    signal_detail: "Marcus Webb, the 2nd-shift press lead, flagged it not because a gauge told him to but because he'd run that press for years and the sound was 'off' in a way he couldn't fully describe on the work order — he asked us to check the main bearing before his next changeover instead of just logging it and moving on. The bearing was found badly worn on inspection, days from a likely catastrophic failure mid-run.",
    judgment: "Formally add an operator-reported 'sounds different' escalation path that gets a same-day maintenance check, instead of requiring a measurable alarm trigger before maintenance responds.",
    rationale: "Long-tenured operators catch failure precursors that sensors aren't tuned to detect at all — the near-miss only became a save because Marcus's report was acted on immediately instead of waiting for a formal work order through the usual queue.",
    boundaries: "This doesn't work as a blanket policy on equipment with high operator turnover, where 'it sounds different' reports lack the years of baseline experience that made Marcus's flag reliable — there, you need to lean on instrumented monitoring instead, not operator gut feel.",
    entity_map: [
      { type: "role_person", name: "Marcus Webb", detail: "2nd-shift press lead, Press #3" },
      { type: "equipment_asset", name: "Press #3", detail: "main bearing" },
    ],
  },
  {
    expert: "tom", daysAgo: 40, trigger_type: "judgment", method: "cdm",
    context_summary: "Sr. Manager of Maintenance decided to run Press #3 through the end of the quarter on a temporary repair rather than force an emergency full rebuild mid-order.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "A worn wear-plate on Press #3 was flagged during a routine check, mid-way through the plant's biggest order of the quarter, and the manufacturer's manual recommended an immediate full rebuild.",
    signal_detail: "The wear-plate was degraded but the failure mode for that specific part is gradual and self-announcing — vibration and noise increase well before it becomes dangerous — unlike the sudden hydraulic valve failures we normally see on that press. That gave us a real, monitorable margin the manual's blanket recommendation didn't account for.",
    judgment: "Run the press through the current order on a temporary shim fix with daily vibration checks, and schedule the full rebuild for the planned quarter-end downtime window instead of stopping the order immediately.",
    rationale: "The manufacturer's recommendation is written for the worst case across all customers and doesn't know this specific failure mode gives visible warning — trusting our own monitoring let us protect the order without taking on the failure-mode risk the manual was actually warning against.",
    boundaries: "This call is wrong for any failure mode that doesn't give a gradual, monitorable warning — the hydraulic valve failures on this same press are sudden, not gradual, and would NOT be safe to defer this way. The judgment only applies to the specific wear-plate failure mode, not to every deferred-maintenance decision on this asset.",
    entity_map: [
      { type: "equipment_asset", name: "Press #3", detail: "wear-plate" },
      { type: "process", name: "Deferred maintenance scheduling", detail: null },
    ],
  },

  // ─── Angela Brooks (sr_manager) ───
  {
    expert: "angela", daysAgo: 6, trigger_type: "win", method: "aar_success_case",
    context_summary: "Sr. Manager of 2nd Shift Production credited a record-output day partly to a changeover staging method that had spread onto her shift.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Process failure", intervention_type: "Re-sequence",
    trigger_signal: "2nd shift posted its highest single-day output in over a year, and the obvious first read was that it was just a good day with no absences and clean materials.",
    signal_detail: "What was actually different was that every changeover that day used the pre-staging method Marcus Webb had built on his own shift and had since started teaching informally to other leads — the crews weren't working harder, the changeovers were just 25-30 minutes shorter each, which is where the extra output actually came from when I added up the time.",
    judgment: "Make pre-staging Marcus's method a standing agenda item in every shift handoff meeting, not just something leads pick up informally if they happen to talk to him.",
    rationale: "Crediting the record day to 'a good day' would have meant nobody deliberately protected or spread the actual cause — naming the real driver means it becomes something we manage on purpose instead of something that shows up by luck.",
    boundaries: "This read would be wrong if headcount, absenteeism, or material quality actually WAS unusually favorable that day too — you have to rule out the obvious explanations before crediting a process change; here the schedule and materials were checked and were both completely ordinary.",
    entity_map: [
      { type: "role_person", name: "Marcus Webb", detail: "2nd-shift press lead" },
      { type: "process", name: "Die changeover staging", detail: null },
      { type: "department", name: "2nd Shift Production", detail: null },
    ],
  },
  {
    expert: "angela", daysAgo: 2, trigger_type: "concern", method: "premortem",
    context_summary: "Sr. Manager of 2nd Shift Production raised a concern about a planned headcount reduction on her shift ahead of next quarter's budget cycle.",
    context_org_size: "200-1000", context_function: "Ops", situation_type: "Headcount/structure", intervention_type: "Consolidate",
    trigger_signal: "Finance proposed cutting one headcount from 2nd shift's crew, reading current throughput-per-person as evidence the shift was slightly overstaffed relative to 1st shift's ratio.",
    signal_detail: "The 'extra' person on paper is the slack that lets someone leave their station to double-check something that looks off — like Marcus's bearing catch — without stopping the line. The throughput math treats every hour as identical, but it can't see the difference between a crew that's exactly busy and a crew that has just enough slack to catch problems before they become failures.",
    judgment: "Push back on the headcount cut for this shift specifically and propose measuring near-miss catches, not just throughput-per-person, before deciding staffing ratios shift by shift.",
    rationale: "Cutting the position that provides slack capacity would save a visible cost while removing an invisible benefit that doesn't show up in any report until the next preventable failure happens — the near-miss catch record is the evidence that benefit is real, not hypothetical.",
    boundaries: "This argument doesn't hold on shifts or lines with genuinely idle time and no history of catches to point to — the case here rests on this specific shift's demonstrated near-miss record, not on staffing slack being valuable everywhere by default.",
    entity_map: [
      { type: "department", name: "2nd Shift Production", detail: null },
      { type: "department", name: "Finance", detail: null },
    ],
  },
];

// ─── helpers ───
async function ensureDemoOrg() {
  const { data: existing } = await supabase
    .from("orgs")
    .select("id")
    .eq("name", DEMO_ORG_NAME)
    .maybeSingle();
  if (existing) return existing.id;
  const { data: created, error } = await supabase
    .from("orgs")
    .insert({ name: DEMO_ORG_NAME, is_demo: true })
    .select("id")
    .single();
  if (error) throw new Error(`Could not create demo org: ${error.message}`);
  return created.id;
}

async function findUserByEmail(email) {
  // No direct getUserByEmail in supabase-js v2's admin API — page through
  // listUsers. Fine at demo scale (a handful of users on this project).
  let page = 1;
  for (;;) {
    const { data, error } = await supabase.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw new Error(`listUsers failed: ${error.message}`);
    const found = data.users.find((u) => u.email === email);
    if (found) return found;
    if (data.users.length < 200) return null;
    page++;
  }
}

async function ensureExpertUser(expert) {
  let user = await findUserByEmail(expert.email);
  if (!user) {
    const { data, error } = await supabase.auth.admin.createUser({
      email: expert.email,
      password: DEMO_PASSWORD,
      email_confirm: true,
    });
    if (error) throw new Error(`createUser(${expert.email}) failed: ${error.message}`);
    user = data.user;
  }
  return user;
}

async function waitForProfile(userId) {
  // handle_new_user() trigger fires async-ish on insert into auth.users;
  // give it a few tries before giving up.
  for (let i = 0; i < 10; i++) {
    const { data } = await supabase.from("profiles").select("id").eq("id", userId).maybeSingle();
    if (data) return;
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`profiles row never appeared for user ${userId}`);
}

async function main() {
  console.log(`Demo org: "${DEMO_ORG_NAME}"`);
  const orgId = await ensureDemoOrg();
  console.log(`  org_id = ${orgId}`);

  const expertIds = {};
  for (const expert of EXPERTS) {
    const user = await ensureExpertUser(expert);
    await waitForProfile(user.id);
    const { error } = await supabase
      .from("profiles")
      .update({
        org_id: orgId,
        persona: expert.persona,
        display_name: expert.display_name,
        updated_at: new Date().toISOString(),
      })
      .eq("id", user.id);
    if (error) throw new Error(`profile update failed for ${expert.email}: ${error.message}`);
    expertIds[expert.key] = user.id;
    console.log(`  ${expert.display_name} (${expert.persona}) → ${user.id}`);
  }

  const { count: existingCount } = await supabase
    .from("pattern_records")
    .select("id", { count: "exact", head: true })
    .eq("org_id", orgId);

  if (existingCount >= RECORDS.length && !FORCE) {
    console.log(
      `Demo org already has ${existingCount} pattern_records (expected ${RECORDS.length}) — skipping seed. Pass --force to reseed.`
    );
    console.log(`\nLogin for any seeded expert: <their email> / ${DEMO_PASSWORD}`);
    return;
  }

  if (FORCE && existingCount > 0) {
    console.log(`--force: deleting ${existingCount} existing demo pattern_records for this org...`);
    const { error } = await supabase.from("pattern_records").delete().eq("org_id", orgId);
    if (error) throw new Error(`delete failed: ${error.message}`);
  }

  const now = Date.now();
  let inserted = 0;
  for (const rec of RECORDS) {
    const userId = expertIds[rec.expert];
    const fields = {
      context_summary: rec.context_summary,
      context_org_size: rec.context_org_size,
      context_industry: "Manufacturing",
      context_function: rec.context_function,
      situation_type: rec.situation_type,
      intervention_type: rec.intervention_type,
      trigger_signal: rec.trigger_signal,
      signal_detail: rec.signal_detail,
      judgment: rec.judgment,
      rationale: rec.rationale,
      boundaries: rec.boundaries,
      entity_map: rec.entity_map,
    };

    console.log(`Framing "${fields.context_summary.slice(0, 60)}..." (${rec.expert}, ${rec.trigger_type}/${rec.method})`);
    const framework = await framePattern(fields);
    if (!framework) {
      console.error(`  ⚠️ framePattern failed after retries — skipping this record`);
      continue;
    }

    const sessionStart = new Date(now - rec.daysAgo * 24 * 60 * 60 * 1000);
    // Time-to-first-value: a plausible 6-14 minute session, varied per record
    // rather than identical, so P-4.5/analytics don't see a suspicious constant.
    const ttfvSeconds = 360 + (rec.daysAgo % 7) * 90;
    const framedAt = new Date(sessionStart.getTime() + ttfvSeconds * 1000);
    const qaPairs = buildQaPairs(fields, rec.method);

    const { error } = await supabase.from("pattern_records").insert({
      user_id: userId,
      qa_pairs: qaPairs,
      pending_question: null,
      pending_rung: null,
      status: "complete",
      trigger_type: rec.trigger_type,
      method: rec.method,
      scrub_status: "not_scrubbed_by_design",
      ...fields,
      framework,
      session_start: sessionStart.toISOString(),
      framework_rendered_at: framedAt.toISOString(),
      time_to_first_value_seconds: ttfvSeconds,
      created_at: sessionStart.toISOString(),
      updated_at: framedAt.toISOString(),
    });
    if (error) {
      console.error(`  ⚠️ insert failed: ${error.message}`);
      continue;
    }
    inserted++;
    console.log(`  ✓ "${framework.name}"`);
  }

  console.log(`\nSeeded ${inserted}/${RECORDS.length} pattern_records for ${DEMO_ORG_NAME}.`);
  console.log(`Login for any seeded expert: <their email> / ${DEMO_PASSWORD}`);
  console.log(`Experts: ${EXPERTS.map((e) => `${e.display_name} <${e.email}>`).join(", ")}`);
  console.log(
    `Corroboration clusters to check in the library / P-4.5 later: "Marcus Webb" (win records — Elena, Tom, Angela), "Denise Ortiz" (win records — David, Priya).`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
