// TIER 1 / BUILD 1 — INVITE A PERSON.
//
// POST { email, display_name, role, claimed_title?, manager_id?, persona? }
//   → creates the seat in the caller's org and returns a sign-in link the
//     admin copies and sends. NO SQL, no seed script, no Brian.
//
// ⭐ THE INVITE MECHANISM (decision, see supabase/t1b1-admin-console.sql and
// the invite section of src/lib/org-admin.ts): COPY-A-LINK, not email. Nothing
// in this codebase sends mail today, and Supabase's built-in SMTP is rate-
// limited below what a live onboarding session needs. The link is generated by
// Supabase's own admin API — this app never creates, sees, or stores a
// password, and never stores the token either.
//
// ⚠️ CROSS-ORG SAFETY: if the email already belongs to somebody in ANOTHER
// org, this refuses. Silently re-homing an existing account would move that
// person's captured judgment across a tenant boundary — the one thing the org
// model exists to prevent.
import { NextRequest, NextResponse } from "next/server";
import { createClient as createSessionClient } from "@/lib/supabase/server";
import {
  cleanText,
  findAuthUserByEmail,
  generateInviteLink,
  generateSignInLink,
  isPersonaValue,
  isRole,
  isValidEmail,
  requestOrigin,
  requireOrgAdmin,
  serviceClient,
  waitForProfile,
} from "@/lib/org-admin";

export async function POST(req: NextRequest) {
  try {
    const session = await createSessionClient();
    const gate = await requireOrgAdmin(session);
    if (!gate.ok) {
      return NextResponse.json({ error: gate.error, code: gate.code }, { status: gate.status });
    }
    const { ctx } = gate;

    const body = await req.json().catch(() => ({}));

    const email = typeof body?.email === "string" ? body.email.trim().toLowerCase() : "";
    if (!isValidEmail(email)) {
      return NextResponse.json({ error: "That doesn't look like an email address." }, { status: 400 });
    }

    const displayName = cleanText(body?.display_name, 80);
    if (!displayName) {
      return NextResponse.json(
        { error: "A name is required — it's what shows on everything they capture." },
        { status: 400 }
      );
    }

    const role = body?.role ?? "member";
    if (!isRole(role)) {
      return NextResponse.json({ error: "Role must be member or manager." }, { status: 400 });
    }

    const claimedTitle = cleanText(body?.claimed_title, 120) ?? null;

    const persona = body?.persona;
    if (persona !== undefined && persona !== null && !isPersonaValue(persona)) {
      return NextResponse.json({ error: "Unknown persona." }, { status: 400 });
    }

    const service = serviceClient();

    // The manager, if one was named, MUST be in this org. Checked against the
    // org, not just against existence.
    const managerId = typeof body?.manager_id === "string" && body.manager_id ? body.manager_id : null;
    if (managerId) {
      const { data: mgr } = await service
        .from("profiles")
        .select("id, org_id, deactivated_at")
        .eq("id", managerId)
        .maybeSingle();
      const mgrRow = mgr as { org_id: string | null; deactivated_at: string | null } | null;
      if (!mgrRow || mgrRow.org_id !== ctx.orgId) {
        return NextResponse.json({ error: "That manager isn't on this account." }, { status: 400 });
      }
      if (mgrRow.deactivated_at) {
        return NextResponse.json(
          { error: "That manager's seat is deactivated — pick an active one." },
          { status: 400 }
        );
      }
    }

    // Org defaults fill in what the admin didn't specify.
    const { data: orgRow } = await service
      .from("orgs")
      .select("default_persona")
      .eq("id", ctx.orgId)
      .maybeSingle();
    const orgDefaultPersona = (orgRow as { default_persona: string | null } | null)?.default_persona ?? null;
    const finalPersona = (persona as string | null | undefined) ?? orgDefaultPersona ?? "sr_manager";

    const origin = requestOrigin(req.headers, req.nextUrl.origin);

    // ─── Does this email already exist in auth? ───
    let existing: { id: string; email: string | null } | null = null;
    try {
      existing = await findAuthUserByEmail(service, email);
    } catch (err) {
      return NextResponse.json(
        {
          error: "Couldn't check whether that email is already in use.",
          details: err instanceof Error ? err.message : String(err),
        },
        { status: 500 }
      );
    }

    let userId: string;
    let link;
    let reused = false;

    if (existing) {
      const { data: prof } = await service
        .from("profiles")
        .select("org_id, deactivated_at")
        .eq("id", existing.id)
        .maybeSingle();
      const profRow = prof as { org_id: string | null; deactivated_at: string | null } | null;

      if (profRow?.org_id && profRow.org_id !== ctx.orgId) {
        return NextResponse.json(
          {
            error:
              "That email is already on another team's account. Ask them to leave that one first — we won't move someone's captured work across organizations.",
            code: "OTHER_ORG",
          },
          { status: 409 }
        );
      }
      if (profRow?.org_id === ctx.orgId && !profRow.deactivated_at) {
        return NextResponse.json(
          { error: "That person is already on this account.", code: "ALREADY_MEMBER" },
          { status: 409 }
        );
      }

      // Orphan account (no org) or a previously deactivated seat on THIS org:
      // adopt it rather than creating a duplicate person.
      userId = existing.id;
      reused = true;
      const gen = await generateSignInLink(service, email, origin);
      if (!gen.ok) return NextResponse.json({ error: gen.error }, { status: 500 });
      link = gen.link;
    } else {
      const gen = await generateInviteLink(service, email, origin);
      if (!gen.ok) return NextResponse.json({ error: gen.error }, { status: 500 });
      userId = gen.userId;
      link = gen.link;
    }

    // handle_new_user() lands the profile row on a trigger — without this wait
    // the UPDATE below can affect zero rows and the person joins no org.
    const ready = await waitForProfile(service, userId);
    if (!ready) {
      return NextResponse.json(
        {
          error:
            "The account was created but its profile hasn't appeared yet. Wait a moment and re-send the invite — it will pick up where it left off.",
          code: "PROFILE_NOT_READY",
        },
        { status: 503 }
      );
    }

    const { error: updateError } = await service
      .from("profiles")
      .update({
        org_id: ctx.orgId,
        display_name: displayName,
        claimed_title: claimedTitle,
        role,
        persona: finalPersona,
        manager_id: managerId,
        invited_at: new Date().toISOString(),
        invited_by: ctx.user.id,
        // Re-inviting a deactivated seat reopens it. Explicit, not implied.
        deactivated_at: null,
        deactivated_by: null,
        updated_at: new Date().toISOString(),
      })
      .eq("id", userId);

    if (updateError) {
      return NextResponse.json(
        { error: "The account exists but the seat couldn't be set up.", details: updateError.message },
        { status: 500 }
      );
    }

    // If the seat was previously deactivated we may also have banned the auth
    // user — lift it so the link actually works. Non-fatal: report, don't fail.
    let signInRestored: boolean | null = null;
    if (reused) {
      const { error: banError } = await service.auth.admin.updateUserById(userId, {
        ban_duration: "none",
      });
      signInRestored = !banError;
    }

    return NextResponse.json({
      success: true,
      member_id: userId,
      email,
      reused_existing_account: reused,
      sign_in_restored: signInRestored,
      invite_link: link.url,
      invite_kind: link.kind,
      invite_expires_hint: link.expires_hint,
    });
  } catch (err) {
    console.error("Unexpected error in admin invite route:", err);
    return NextResponse.json({ error: "Unexpected server error" }, { status: 500 });
  }
}
